#ifndef __fixedsized_msgs__msg__FixedImageVgaMono8__idl
#define __fixedsized_msgs__msg__FixedImageVgaMono8__idl

#include "FixedHeader.idl"
#include "FixedString32.idl"

module fixedsized_msgs { module msg {

struct FixedImageVgaMono8 {
    fixedsized_msgs::msg::FixedHeader header;
    unsigned long height;
    unsigned long width;
    fixedsized_msgs::msg::FixedString32 encoding;
    boolean is_bigendian;
    unsigned long step;
    octet data[307200];
};

}; };  // module msg::fixedsized_msgs

#endif
